/*{
    "DESCRIPTION": "Apollonian sphere packing finished in thin-film iridescence. The geometry is built by repeated inversion in spheres, so every sphere nestles in the gap left by the last and the packing continues to any depth. The surface colour is not a palette: it is the interference of light reflecting off the front and back of a nanometre-scale film, computed per wavelength with Snell refraction through the film, which is the same physics that colours a soap bubble and anodised titanium. Lit by a procedural studio and reflected off itself. Bass drives the packing constant, beats swell the film, spectral centroid tilts the key light.",
    "CREDIT": "Ghost Arcade 2.0 pack",
    "ISFVSN": "2",
    "CATEGORIES": ["Generator", "3D Room", "Audio Reactive"],
    "INPUTS": [
        {"NAME": "colorMode", "TYPE": "long", "DEFAULT": 0,
         "VALUES": [0, 1, 2, 3, 4, 5, 6],
         "LABELS": ["Bubble", "Oilslick", "Anodised", "Pearl", "Bismuth", "Platinum", "Peacock"]},
        {"NAME": "radius",    "TYPE": "float", "DEFAULT": 1.05, "MIN": 0.55, "MAX": 2.60},
        {"NAME": "zoom",      "TYPE": "float", "DEFAULT": 1.00, "MIN": 0.45, "MAX": 2.20},
        {"NAME": "packing",   "TYPE": "float", "DEFAULT": 1.28, "MIN": 1.02, "MAX": 1.60},
        {"NAME": "film",      "TYPE": "float", "DEFAULT": 1.00, "MIN": 0.20, "MAX": 3.00},
        {"NAME": "polish",    "TYPE": "float", "DEFAULT": 0.75, "MIN": 0.00, "MAX": 1.00},
        {"NAME": "orbitSpin", "TYPE": "float", "DEFAULT": 0.22, "MIN": 0.00, "MAX": 1.50},
        {"NAME": "churn",     "TYPE": "float", "DEFAULT": 0.30, "MIN": 0.00, "MAX": 1.50},
        {"NAME": "hueShift",  "TYPE": "float", "DEFAULT": 0.00, "MIN": 0.00, "MAX": 1.00},
        {"NAME": "exposure",  "TYPE": "float", "DEFAULT": 1.00, "MIN": 0.20, "MAX": 2.00}
    ]
}*/

#ifdef GL_ES
precision highp float;
#endif

/*
 * Apollonian packing, finished in thin film.
 *
 * GEOMETRY. Apollonius: given three mutually tangent circles there are exactly
 * two more tangent to all three. Iterate that and every gap spawns a smaller
 * circle for ever. In 3D the same construction is generated by inversion in a
 * sphere -- p -> p * s/|p|^2 -- alternated with a fold that brings space back
 * into the fundamental domain. Each pass is a similarity, so tracking the
 * accumulated scale converts a distance measured in the folded space back into
 * world units. Eight passes give a packing dense enough that the eye stops
 * counting spheres and starts reading it as a material.
 *
 * MATERIAL. The colour is not chosen. A film a few hundred nanometres thick
 * reflects light off both its surfaces; the two reflections travel different
 * distances and interfere, constructively at some wavelengths and destructively
 * at others, and what survives is the colour. The optical path difference is
 *
 *     OPD = 2 n d cos(theta_t)
 *
 * with theta_t the angle INSIDE the film, which is why the hue slides as the
 * surface turns away -- the light takes a longer path through the film at
 * grazing angles. Evaluating the interference at 650, 550 and 450 nm gives the
 * RGB response directly. This is the physics of a soap bubble and of anodised
 * titanium, and it is why the colour holds together across the whole surface
 * instead of looking painted on: every hue on screen is the same film seen at a
 * different angle and thickness.
 *
 * LIGHT. A procedural studio -- key, fill, rim, and a graded ground -- is
 * sampled along the reflected ray. Reflections are what make a dense fractal
 * read as an object rather than a pattern, because they tie its curvature to a
 * consistent surrounding.
 */

const float PI = 3.14159265359;
const float PI2 = 6.28318530718;
const int APOLLO_ITERS = 8;
const int MAX_STEPS = 130;

/*
 * Apollonian distance estimate. `s` is the inversion constant: how hard each
 * pass pushes space through the sphere, and therefore how tightly the packing
 * closes. The returned orbit trap records the closest approach, which tracks
 * how deep into the packing a point sits.
 */
float apollonian(vec3 p, float s, out float trap) {
    float scale = 1.0;
    trap = 1e9;
    for (int i = 0; i < APOLLO_ITERS; i++) {
        /* Fold back into the fundamental domain. */
        p = -1.0 + 2.0 * fract(0.5 * p + 0.5);
        float r2 = dot(p, p);
        trap = min(trap, r2);
        /* Inversion in the unit sphere, scaled. Each pass is a similarity, so
           the accumulated factor converts folded distance back to world. */
        float k = s / r2;
        p *= k;
        scale *= k;
    }
    /* Distance to a plane in the folded space, undone by the accumulated
       scale. Conservative factor: this estimate overshoots near tangencies,
       and an overstep there punches holes straight through a sphere. */
    return 0.22 * abs(p.y) / scale;
}

/*
 * The packing carved down to a ball, so there is an object to orbit rather than
 * a space to fly through.
 *
 * `bound` is exposed rather than fixed because the packing is space-filling:
 * widening the ball does not scale the same cluster up, it admits MORE of the
 * packing, so new spheres appear at the rim instead of the existing ones simply
 * growing. That is a different picture, not a zoom, which is why framing gets
 * its own control.
 */
float mapScene(vec3 p, float s, float bound, out float trap) {
    float d = apollonian(p, s, trap);
    return max(d, length(p) - bound);
}

vec3 sceneNormal(vec3 p, float s, float bound) {
    vec2 e = vec2(1.0, -1.0) * 0.0016;
    float t;
    return normalize(
        e.xyy * mapScene(p + e.xyy, s, bound, t) +
        e.yyx * mapScene(p + e.yyx, s, bound, t) +
        e.yxy * mapScene(p + e.yxy, s, bound, t) +
        e.xxx * mapScene(p + e.xxx, s, bound, t));
}

/*
 * Thin-film interference.
 *
 * `d` is film thickness in nanometres, `cosI` the cosine of the incidence angle
 * outside the film, `n` its refractive index. Snell gives the angle inside;
 * the optical path difference across one round trip sets the phase; the two
 * reflections interfere. Evaluated at three wavelengths for RGB.
 */
vec3 thinFilm(float d, float cosI, float n) {
    float sinI2 = max(1.0 - cosI * cosI, 0.0);
    float cosT = sqrt(max(1.0 - sinI2 / (n * n), 0.0));   /* Snell, inside */
    float opd = 2.0 * n * d * cosT;                       /* path difference  */
    vec3 lambda = vec3(650.0, 545.0, 450.0);              /* R, G, B in nm    */
    /* Half-wave shift at the front reflection puts the pi offset in. */
    vec3 phase = PI2 * opd / lambda + PI;
    return 0.5 + 0.5 * cos(phase);
}

/*
 * Procedural studio. Sampled along the reflected ray, so the fractal picks up a
 * consistent surrounding and reads as a solid object.
 */
vec3 studio(vec3 dir, float tilt) {
    float up = dir.y * 0.5 + 0.5;
    vec3 ground = vec3(0.010, 0.011, 0.014);
    vec3 sky = vec3(0.085, 0.100, 0.135);
    vec3 base = mix(ground, sky, smoothstep(0.0, 1.0, up));

    vec3 keyDir = normalize(vec3(0.42 + 0.25 * tilt, 0.78, 0.46));
    vec3 fillDir = normalize(vec3(-0.75, 0.18, 0.32));
    vec3 rimDir = normalize(vec3(0.10, -0.24, -0.94));

    float key = pow(max(dot(dir, keyDir), 0.0), 34.0);
    float fill = pow(max(dot(dir, fillDir), 0.0), 9.0);
    float rim = pow(max(dot(dir, rimDir), 0.0), 20.0);

    return base
         + vec3(1.00, 0.97, 0.92) * key * 5.0
         + vec3(0.42, 0.55, 0.85) * fill * 0.55
         + vec3(0.85, 0.80, 1.00) * rim * 1.30;
}

/*
 * Palettes for this shader alone. These are not hue ramps: the colour comes out
 * of the interference maths, so a "palette" here is a film -- its thickness
 * range, its refractive index, and the tint of the metal underneath it.
 * Thickness sets which interference orders land in the visible band, which is
 * what separates a soap bubble from an oil slick from anodised titanium.
 *
 * Columns: [ (thicknessNm, indexN, orderSpread), substrateTint, specTint ].
 */
mat3 filmFor(int mode) {
    vec3 spec = vec3(1.0, 0.98, 0.95);
    if (mode == 1) {            /* Oilslick - thick, many orders, warm base */
        return mat3(vec3(720.0, 1.42, 320.0), vec3(0.10, 0.08, 0.07), spec);
    } else if (mode == 2) {     /* Anodised - titanium oxide, teal to violet */
        return mat3(vec3(430.0, 2.20, 130.0), vec3(0.07, 0.09, 0.11), spec);
    } else if (mode == 3) {     /* Pearl - very thin, pale and shifting */
        return mat3(vec3(260.0, 1.34, 90.0), vec3(0.30, 0.29, 0.31), spec);
    } else if (mode == 4) {     /* Bismuth - thick, hard-stepped bands */
        return mat3(vec3(980.0, 2.05, 480.0), vec3(0.09, 0.07, 0.10), spec);
    } else if (mode == 5) {     /* Platinum - near-neutral, specular carries it */
        return mat3(vec3(150.0, 1.20, 40.0), vec3(0.52, 0.54, 0.58), spec);
    } else if (mode == 6) {     /* Peacock - blues and golds, mid film */
        return mat3(vec3(560.0, 1.90, 210.0), vec3(0.04, 0.08, 0.10), spec);
    }
    /* Bubble - the classic: thin, low index, full sweep */
    return mat3(vec3(380.0, 1.33, 180.0), vec3(0.05, 0.06, 0.08), spec);
}

/*
 * The visible backdrop, kept SEPARATE from the reflection environment.
 *
 * studio() is deliberately bright -- it has to be, or the reflections have no
 * highlights to catch. Showing that same environment behind the object floods
 * the frame with mid-grey and the silhouette disappears into it, which is
 * exactly what happened when the two were shared. Every product shot resolves
 * this the same way: light the subject hard, keep the ground dark.
 */
vec3 backdrop(vec2 uv, vec3 tint) {
    float r = length(uv);
    vec3 near = vec3(0.024, 0.028, 0.038) + tint * 0.02;
    vec3 far = vec3(0.004, 0.005, 0.008);
    return mix(near, far, smoothstep(0.0, 1.15, r));
}

void main() {
    vec2 uv = (gl_FragCoord.xy - 0.5 * RENDERSIZE.xy) / RENDERSIZE.y;

    /* Idle fallbacks so the packing still churns with nothing bound. */
    float bass = max(audioBass, 0.24 + 0.10 * sin(TIME * 0.23));
    float level = max(audioLevel, 0.20 + 0.08 * sin(TIME * 0.17));
    float centroid = max(audioSpectralCentroid, 0.44 + 0.16 * sin(TIME * 0.11));
    float beat = audioBeat;

    /* The packing constant. Small changes here reorganise the whole cluster,
       so it is kept on a narrow leash and moved slowly. */
    float s = packing + 0.05 * sin(TIME * churn * 0.7) + 0.03 * bass;

    mat3 f = filmFor(int(colorMode));
    float baseNm = f[0].x;
    float filmN = f[0].y;
    float spread = f[0].z;
    vec3 SUBSTRATE = f[1];
    vec3 SPECTINT = f[2];

    /* Camera orbits the ball. Distance tracks the radius so a wider ball stays
       framed, and `zoom` then pushes in or pulls out from there -- one control
       for how much packing is shown, another for how much of the frame it
       fills. */
    float bound = radius;
    float camDist = (2.55 + bound * 1.55) / max(zoom, 0.05);
    float ang = TIME * orbitSpin;
    vec3 ro = vec3(sin(ang) * camDist, (0.18 + 0.55 * bound) + 0.40 * sin(TIME * 0.15), cos(ang) * camDist);
    vec3 fwd = normalize(-ro);
    vec3 right = normalize(cross(vec3(0.0, 1.0, 0.0), fwd));
    vec3 up = cross(fwd, right);
    vec3 rd = normalize(right * uv.x + up * uv.y + fwd * 1.6);

    /* Analytic entry to the bounding ball: rays that miss cost nothing. */
    float bq = dot(ro, rd);
    float disc = bq * bq - dot(ro, ro) + bound * bound;

    vec3 col;

    if (disc < 0.0) {
        col = backdrop(uv, SPECTINT * 0.0);
    } else {
        float hs = sqrt(disc);
        float dist = max(-bq - hs, 0.0);
        float exitAt = -bq + hs;

        float trap = 1e9;
        float steps = 0.0;
        bool hit = false;

        for (int i = 0; i < MAX_STEPS; i++) {
            vec3 p = ro + rd * dist;
            float t;
            float d = mapScene(p, s, bound, t);
            if (d < 0.0007 * dist + 0.00025) {
                trap = t;
                hit = true;
                break;
            }
            dist += d * 0.72;
            steps += 1.0;
            if (dist > exitAt) break;
        }

        if (!hit) {
            col = backdrop(uv, SPECTINT * 0.0);
        } else {
            vec3 p = ro + rd * dist;
            vec3 nrm = sceneNormal(p, s, bound);
            float cosI = clamp(dot(nrm, -rd), 0.0, 1.0);

            /* Film thickness varies over the surface with depth into the
               packing, so tangent spheres carry different interference orders
               and the cluster does not flatten into one hue. */
            float depth = clamp(sqrt(max(trap, 0.0)) * 1.4, 0.0, 1.0);
            float thickness = baseNm
                            + spread * depth
                            + spread * 0.35 * sin(TIME * churn + hueShift * PI2)
                            + spread * 0.25 * beat;
            thickness *= film;

            vec3 irid = thinFilm(thickness, cosI, filmN);

            /* Schlick fresnel, but on a METAL floor rather than a dielectric
               one. A bare 0.04 base is right for glass and wrong for this: it
               reflects almost nothing face-on, so the iridescence only appears
               at the silhouette and the body goes dead grey. Anodised metal is
               what this material actually is -- an oxide film grown on a
               reflective substrate -- and it carries reflectance right across
               the surface, which is where the colour lives. */
            float fres = 0.04 + 0.96 * pow(1.0 - cosI, 5.0);
            float reflAmt = mix(0.42, 1.0, fres);
            reflAmt = mix(0.18, reflAmt, polish);

            vec3 refl = studio(reflect(rd, nrm), centroid - 0.5);

            /* Cavity darkening from the step count. In a packing this dense the
               contact points between spheres are most of what sells the depth,
               and they are exactly where the march grinds. */
            float ao = clamp(1.0 - steps / float(MAX_STEPS), 0.0, 1.0);
            ao = mix(0.12, 1.0, ao * ao);

            vec3 keyDir = normalize(vec3(0.42 + 0.25 * (centroid - 0.5), 0.78, 0.46));
            float diff = clamp(dot(nrm, keyDir), 0.0, 1.0);
            float specPow = mix(18.0, 220.0, polish);
            float spec = pow(clamp(dot(reflect(-keyDir, nrm), -rd), 0.0, 1.0), specPow);

            /* Substrate under the film, then the film-tinted reflection on top,
               then the direct highlight. */
            col = SUBSTRATE * (0.25 + 0.75 * diff) * ao;
            col += refl * irid * reflAmt * ao * (1.05 + 0.60 * level);
            col += SPECTINT * spec * (0.55 + 0.60 * polish) * ao;
            col += irid * pow(1.0 - cosI, 3.0) * 0.26 * ao;   /* rim bloom */

            col *= 1.0 + beat * 0.22;

            /* Barely any fog. The whole object spans about two units, so a
               haze tuned for a landscape buries it -- the previous rate washed
               the entire cluster into the backdrop. */
            float fog = 1.0 - exp(-max(dist - (camDist - bound * 0.4), 0.0) * 0.22);
            col = mix(col, backdrop(uv, vec3(0.0)), fog * 0.5);
        }
    }

    col *= exposure;
    col = col / (1.0 + col);
    col = pow(max(col, 0.0), vec3(0.4545));

    gl_FragColor = vec4(col, 1.0);
}
