import type { EffectType } from '../types';
import type { EffectTier } from '$lib/license/featureGates';
import { getEffectTier } from '$lib/license/featureGates';

export interface EffectCatalogEntry {
  type: EffectType;
  label: string;
  category: string;
  description: string;
  previewCSS: string; // CSS background for preview thumbnail
  tier: EffectTier;   // Required license tier (auto-derived from category)
  /**
   * If true, the effect requires a working WebGPU device. The picker hides
   * (or locks, depending on UI mode) the entry on browsers/devices where
   * WebGPU is not available so users don't try to add an effect that will
   * silently no-op.
   */
  requiresWebGPU?: boolean;
  requiresNative?: boolean;
}

// Internal type without tier — we compute tier from category below
type RawEntry = Omit<EffectCatalogEntry, 'tier'>;

// Single source of truth for effect availability in Mapper + VJ.
// 81 curated effects organized into 17 categories. Order here drives
// the order in the EffectPickerModal accordion — keep "basics" near the
// top, "advanced" sections grouped at the bottom.
//
// Category renames vs older versions:
//   "Generate"          → "Generate & Texture"
//   "Advanced Text"     → "Advanced Text & Pattern"
// Also: Advanced Warp's late-added effects (fractalWarp, fluidDistort,
// wormhole) are now consolidated with the rest of the category instead
// of dangling at the bottom of the file.
const RAW_CATALOG: RawEntry[] = [
  { type: 'cubeLut', requiresNative: true, label: 'Color LUT', category: 'Color', description: 'Import a 3D .cube color look. GPU grading with adjustable strength; the LUT travels with your project.', previewCSS: 'linear-gradient(135deg, #16386b, #bd6585, #e8b475)' },
  // ── WebGPU (1) — GPU-edition exclusive ──
  { type: 'gpuFluidSim', label: 'Fluid Sim', category: 'WebGPU',
    description: 'Real-time Navier-Stokes fluid simulation on GPU compute. The source feeds dye + force into the fluid; colors swirl, billow, and dissipate like watercolor in water. Try over a video for surreal flowing imagery.',
    previewCSS: 'radial-gradient(circle at 30% 70%, #06f 0%, #08f 20%, #0cf 35%, #f80 55%, #f44 75%, #311 95%)',
    requiresWebGPU: true },
  { type: 'eulerianMagnify', label: 'Eulerian Magnify', category: 'Vision Lab',
    description: 'Live Eulerian/phase-style video magnification. Band-pass subtle color pulses or tiny motion from ordinary camera/video sources, amplify them, or attenuate them.',
    previewCSS: 'radial-gradient(circle at 40% 45%, #ffd0c8 0%, #ff6060 16%, #3b0d1d 28%, transparent 44%), repeating-radial-gradient(circle at 50% 50%, #0ff4 0px, #0ff1 4px, transparent 9px, transparent 18px), #06070a' },

  // ── Masking (2) ──
  { type: 'vignette', label: 'Vignette', category: 'Masking',
    description: 'Fade edges to transparent with adjustable shape',
    previewCSS: 'radial-gradient(ellipse at center, #fff 30%, transparent 70%)' },
  { type: 'edgeFeather', label: 'Edge Feather', category: 'Masking',
    description: 'Independent soft feathering on each edge',
    previewCSS: 'linear-gradient(to right, transparent 5%, #fff 20%, #fff 80%, transparent 95%)' },

  // ── Color (15) ──
  { type: 'colorama', label: 'Colorama', category: 'Color',
    description: 'Map luminance to cycling color palettes — named palettes, audio cycling, posterized bands',
    previewCSS: 'linear-gradient(90deg, #f0f, #ff0, #0ff, #f0f)' },
  { type: 'plasma', label: 'Plasma', category: 'Color',
    description: 'Animated plasma color overlay',
    previewCSS: 'radial-gradient(circle at 30% 40%, #f0f, #00f, #0ff, #ff0)' },
  { type: 'invert', label: 'Invert', category: 'Color',
    description: 'Invert all colors',
    previewCSS: 'linear-gradient(135deg, #000 0%, #fff 50%, #000 100%)' },
  { type: 'posterize', label: 'Posterize', category: 'Color',
    description: 'Reduce color levels for a poster look',
    previewCSS: 'linear-gradient(90deg, #000 0%, #000 25%, #555 25%, #555 50%, #aaa 50%, #aaa 75%, #fff 75%)' },
  { type: 'exposure', label: 'Exposure', category: 'Color',
    description: 'Photographic exposure adjustment',
    previewCSS: 'linear-gradient(135deg, #333 0%, #999 50%, #fff 100%)' },
  { type: 'gamma', label: 'Gamma', category: 'Color',
    description: 'Gamma curve brightness correction',
    previewCSS: 'linear-gradient(135deg, #222 0%, #888 30%, #ddd 100%)' },
  { type: 'vibrance', label: 'Vibrance', category: 'Color',
    description: 'Boost muted colors without clipping saturated ones',
    previewCSS: 'linear-gradient(135deg, #a88 0%, #f44 50%, #f88 100%)' },
  { type: 'temperatureTint', label: 'Temperature / Tint', category: 'Color',
    description: 'Warm/cool white balance with green-magenta tint',
    previewCSS: 'linear-gradient(90deg, #48f 0%, #fff 50%, #fa4 100%)' },
  { type: 'colorBalance', label: 'Color Balance', category: 'Color',
    description: 'Shift color balance across RGB channels',
    previewCSS: 'linear-gradient(135deg, #f88 0%, #8f8 50%, #88f 100%)' },
  { type: 'curves', label: 'Curves', category: 'Color',
    description: 'RGB gamma curve adjustments',
    previewCSS: 'linear-gradient(135deg, #400 0%, #040 50%, #004 100%)' },
  { type: 'liftGammaGain', label: 'Lift / Gamma / Gain', category: 'Color',
    description: 'Three-way color grading for shadows, mids, highlights',
    previewCSS: 'linear-gradient(135deg, #423 0%, #886 50%, #fed 100%)' },
  { type: 'thermal', label: 'Thermal', category: 'Color',
    description: 'Infrared thermal camera look',
    previewCSS: 'linear-gradient(135deg, #008 0%, #f0f 33%, #ff0 66%, #fff 100%)' },
  { type: 'nightVision', label: 'Night Vision', category: 'Color',
    description: 'Military night vision green phosphor look',
    previewCSS: 'radial-gradient(circle at center, #0f0 40%, #030 80%, #010 100%)' },
  { type: 'filmicTonemap', label: 'Filmic Tonemap', category: 'Color',
    description: 'ACES filmic curve — cinematic highlight compression',
    previewCSS: 'linear-gradient(135deg, #111 0%, #665 40%, #cc9 70%, #eed 100%)' },
  { type: 'selectiveColor', label: 'Selective Color', category: 'Color',
    description: 'Target and shift specific hue ranges',
    previewCSS: 'conic-gradient(from 0deg, #f00, #ff0, #0f0, #0ff, #00f, #f0f, #f00)' },

  // ── Stylize (18) — includes blob analysis effects per roadmap ──
  { type: 'dither', label: 'Dither', category: 'Stylize',
    description: 'Retro dithering patterns — Bayer, noise, halftone',
    previewCSS: 'repeating-linear-gradient(45deg, #000 0px, #000 2px, #fff 2px, #fff 4px)' },
  { type: 'edgeDetect', label: 'Edge Detect', category: 'Stylize',
    description: 'Sobel/Laplacian edge detection',
    previewCSS: 'linear-gradient(135deg, #000 0%, #000 45%, #fff 50%, #000 55%, #000 100%)' },
  { type: 'outline', label: 'Outline', category: 'Stylize',
    description: 'Glowing colored edge outlines',
    previewCSS: 'radial-gradient(circle at center, #000 35%, #0ff 38%, #000 42%)' },
  { type: 'emboss', label: 'Emboss', category: 'Stylize',
    description: '3D embossed/raised surface look',
    previewCSS: 'linear-gradient(135deg, #bbb 0%, #888 50%, #555 100%)' },
  { type: 'vhs', label: 'VHS', category: 'Stylize',
    description: 'VHS tape artifacts — tracking, color bleed, scanlines',
    previewCSS: 'linear-gradient(180deg, #433 0%, #554 20%, #766 40%, #433 41%, #655 60%, #433 80%)' },
  { type: 'glitch', label: 'Glitch', category: 'Stylize',
    description: 'Digital glitch with RGB split and block artifacts',
    previewCSS: 'linear-gradient(90deg, #f00 0%, #f00 10%, #0f0 10%, #0f0 15%, #00f 15%, #00f 20%, #888 20%)' },
  { type: 'rgbShift', label: 'RGB Shift', category: 'Stylize',
    description: 'Separate and offset RGB channels',
    previewCSS: 'linear-gradient(0deg, rgba(255,0,0,0.5), transparent), linear-gradient(120deg, rgba(0,255,0,0.5), transparent), linear-gradient(240deg, rgba(0,0,255,0.5), transparent)' },
  { type: 'scanlines', label: 'Scanlines', category: 'Stylize',
    description: 'Animated CRT-style scanline overlay',
    previewCSS: 'repeating-linear-gradient(180deg, transparent 0px, transparent 2px, rgba(0,0,0,0.4) 2px, rgba(0,0,0,0.4) 4px)' },
  { type: 'fmScanlines', label: 'FM Lines', category: 'Stylize',
    description: "Luminance-driven line displacement — brightness pushes scanlines off-baseline and modulates a sine wave's frequency & amplitude, so lit areas churn into dense ripples (the 'FM portrait' look). Horizontal, vertical, or concentric.",
    previewCSS: 'repeating-linear-gradient(180deg, #000 0px, #000 2px, #fff 3px, #000 4px, #000 7px, #fff 8px, #000 9px)' },
  { type: 'phaseLab', label: 'Phase Lab', category: 'Stylize',
    description: 'Source-driven phase/interference looks for any layer: BOS schlieren refraction, photoelastic stress fringes, Lippmann color, InSAR phase wraps, catoptric anamorphosis, and DTI ribbons.',
    previewCSS: 'radial-gradient(circle at 35% 45%, #ff5 0%, #f4a 18%, #67f 36%, #5ff 50%, transparent 66%), repeating-conic-gradient(from 20deg, #101 0deg, #063 18deg, #fd4 36deg, #101 54deg)' },
  { type: 'pixelate', label: 'Pixelate', category: 'Stylize',
    description: 'Mosaic / pixelation effect',
    previewCSS: 'repeating-conic-gradient(#888 0% 25%, #aaa 25% 50%) 0 0/20px 20px' },
  { type: 'halftone', label: 'Halftone', category: 'Stylize',
    description: 'Newspaper-style halftone dots',
    previewCSS: 'radial-gradient(circle, #000 30%, #fff 31%) 0 0/12px 12px' },
  { type: 'toon', label: 'Toon', category: 'Stylize',
    description: 'Cel-shaded cartoon quantization',
    previewCSS: 'linear-gradient(135deg, #222 0%, #222 30%, #888 31%, #888 60%, #eee 61%)' },
  { type: 'kuwahara', label: 'Kuwahara', category: 'Stylize',
    description: 'Painterly smoothing that preserves edges',
    previewCSS: 'radial-gradient(ellipse at 40% 40%, #a86 0%, #864 40%, #642 80%)' },
  { type: 'oilPaint', label: 'Oil Paint', category: 'Stylize',
    description: 'Oil painting with quantized color bands',
    previewCSS: 'linear-gradient(135deg, #a64 0%, #86a 30%, #4a8 60%, #a86 100%)' },
  { type: 'watercolor', label: 'Watercolor', category: 'Stylize',
    description: 'Soft watercolor wash with edge darkening',
    previewCSS: 'radial-gradient(ellipse at 60% 40%, #8ac 0%, #6a8 40%, #486 80%)' },
  { type: 'blobTrack', label: 'Blob Track', category: 'Stylize',
    description: 'GPU blob detection with shape markers, bounding boxes, and coordinate readouts — works on any media including point clouds',
    previewCSS: 'radial-gradient(circle at 30% 40%, #0f4 0%, transparent 20%), radial-gradient(circle at 70% 60%, #0f4 0%, transparent 15%), #111' },
  { type: 'blobContour', label: 'Blob Contour', category: 'Stylize',
    description: 'Edge-detection contour lines with topographic multi-level luminance visualization and optional coordinate overlay',
    previewCSS: 'repeating-radial-gradient(circle at 50% 50%, transparent 0%, #0ff2 5%, transparent 10%), #111' },
  { type: 'blobHeatmap', label: 'Blob Heatmap', category: 'Stylize',
    description: 'Density heat-map overlay with configurable palettes (inferno, viridis, plasma, magma), grid lines, and peak markers',
    previewCSS: 'linear-gradient(180deg, #fcf 0%, #f80 25%, #f00 50%, #800 75%, #200 100%)' },

  // ── Blur & Focus (7) ──
  { type: 'blur', label: 'Blur', category: 'Blur & Focus',
    description: 'Gaussian blur',
    previewCSS: 'radial-gradient(circle at center, #aaa 0%, #888 100%)' },
  { type: 'sharpen', label: 'Sharpen', category: 'Blur & Focus',
    description: 'Unsharp mask sharpening',
    previewCSS: 'linear-gradient(135deg, #000 0%, #fff 48%, #000 52%, #fff 100%)' },
  { type: 'directionalBlur', label: 'Directional Blur', category: 'Blur & Focus',
    description: 'Motion blur along a specified angle',
    previewCSS: 'linear-gradient(0deg, #888 0%, #ccc 40%, #888 50%, #ccc 60%, #888 100%)' },
  { type: 'zoomBlur', label: 'Zoom Blur', category: 'Blur & Focus',
    description: 'Radial zoom blur from center point',
    previewCSS: 'radial-gradient(circle at center, #fff 0%, #888 30%, #ccc 60%, #888 100%)' },
  { type: 'radialBlur', label: 'Radial Blur', category: 'Blur & Focus',
    description: 'Circular/spin blur around center',
    previewCSS: 'conic-gradient(#888, #ccc, #888, #ccc, #888)' },
  { type: 'tiltShift', label: 'Tilt Shift', category: 'Blur & Focus',
    description: 'Miniature/diorama focus band effect',
    previewCSS: 'linear-gradient(180deg, #888 0%, #ccc 35%, #fff 50%, #ccc 65%, #888 100%)' },
  { type: 'defocusBokeh', label: 'Defocus Bokeh', category: 'Blur & Focus',
    description: 'Hexagonal bokeh-shaped out-of-focus blur',
    previewCSS: 'radial-gradient(circle at 30% 40%, rgba(255,255,255,0.6) 5%, transparent 6%), radial-gradient(circle at 70% 30%, rgba(255,255,255,0.5) 4%, transparent 5%), radial-gradient(circle at 50% 70%, rgba(255,255,255,0.4) 6%, transparent 7%), #556' },

  // ── Light & Glow (7) ──
  { type: 'bloom', label: 'Bloom', category: 'Light & Glow',
    description: 'Soft glow around bright areas',
    previewCSS: 'radial-gradient(circle at center, #fff 0%, #ffa 20%, #443 60%, #221 100%)' },
  { type: 'chromaticAberration', label: 'Chromatic Aberration', category: 'Light & Glow',
    description: 'Lens color fringing from center',
    previewCSS: 'radial-gradient(circle at center, #fff 30%, #fcc 50%, #ccf 70%)' },
  { type: 'godRays', label: 'God Rays', category: 'Light & Glow',
    description: 'Volumetric light rays from bright source',
    previewCSS: 'conic-gradient(from 90deg at 50% 20%, transparent, rgba(255,240,200,0.4) 5%, transparent 10%, rgba(255,240,200,0.3) 15%, transparent 20%, rgba(255,240,200,0.2) 30%, transparent 40%), #332' },
  { type: 'halation', label: 'Halation', category: 'Light & Glow',
    description: 'Warm film halation — red glow bleeding from highlights',
    previewCSS: 'radial-gradient(circle at center, #fff 10%, #fca 25%, #f84 40%, #421 70%)' },
  { type: 'anamorphicStreak', label: 'Anamorphic Streak', category: 'Light & Glow',
    description: 'Horizontal light streaks like anamorphic lenses',
    previewCSS: 'linear-gradient(0deg, #221 0%, #221 45%, #8af 48%, #fff 50%, #8af 52%, #221 55%, #221 100%)' },
  { type: 'lensDirt', label: 'Lens Dirt', category: 'Light & Glow',
    description: 'Procedural lens dirt and flare overlay',
    previewCSS: 'radial-gradient(circle at 25% 35%, rgba(255,200,100,0.3) 5%, transparent 10%), radial-gradient(circle at 70% 60%, rgba(200,220,255,0.2) 8%, transparent 15%), radial-gradient(circle at 50% 50%, rgba(255,255,255,0.1) 30%, transparent 60%), #332' },
  { type: 'diffusionPromist', label: 'Diffusion / Pro-Mist', category: 'Light & Glow',
    description: 'Dreamy pro-mist diffusion filter — soft highlight glow',
    previewCSS: 'radial-gradient(circle at center, rgba(255,255,255,0.5) 0%, rgba(255,240,220,0.3) 30%, rgba(200,180,160,0.1) 60%, #443 100%)' },

  // ── Generate & Texture (4) — renamed from "Generate" ──
  { type: 'noise', label: 'Noise', category: 'Generate & Texture',
    description: 'Static or animated noise overlay',
    previewCSS: 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'n\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23n)\'/%3E%3C/svg%3E")' },
  { type: 'filmGrain', label: 'Film Grain', category: 'Generate & Texture',
    description: 'Photographic film grain texture',
    previewCSS: 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'n\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.9\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23n)\'/%3E%3C/svg%3E")' },
  { type: 'heatHaze', label: 'Heat Haze', category: 'Generate & Texture',
    description: 'Animated heat shimmer distortion',
    previewCSS: 'repeating-linear-gradient(180deg, transparent 0px, rgba(200,180,140,0.15) 3px, transparent 6px)' },
  { type: 'crt', label: 'CRT', category: 'Generate & Texture',
    description: 'CRT monitor — scanlines, RGB mask, curvature',
    previewCSS: 'repeating-linear-gradient(180deg, rgba(0,0,0,0.3) 0px, transparent 1px, transparent 3px), repeating-linear-gradient(90deg, rgba(255,0,0,0.3) 0px, rgba(0,255,0,0.3) 1px, rgba(0,0,255,0.3) 2px, rgba(255,0,0,0.3) 3px), #444' },

  // ── Distort (10) ──
  { type: 'kaleidoscope', label: 'Kaleidoscope', category: 'Distort',
    description: 'Mirror symmetry kaleidoscope segments',
    previewCSS: 'conic-gradient(from 0deg, #f48, #4f8, #48f, #f48, #4f8, #48f)' },
  { type: 'mirror', label: 'Mirror', category: 'Distort',
    description: 'Mirror image horizontally, vertically, or both',
    previewCSS: 'linear-gradient(90deg, #468 0%, #468 50%, #864 50%, #864 100%)' },
  { type: 'wave', label: 'Wave', category: 'Distort',
    description: 'Sine wave distortion — horizontal, vertical, radial',
    previewCSS: 'repeating-linear-gradient(90deg, #668 0px, #886 15px, #668 30px)' },
  { type: 'fisheye', label: 'Fisheye', category: 'Distort',
    description: 'Barrel/pincushion lens distortion',
    previewCSS: 'radial-gradient(circle at center, #fff 20%, #aaa 50%, #666 80%)' },
  { type: 'lensDistortion', label: 'Lens Distortion', category: 'Distort',
    description: 'Radial lens barrel/pincushion warp',
    previewCSS: 'radial-gradient(circle at center, #ccc 10%, #999 40%, #666 70%, #333 100%)' },
  { type: 'displacement', label: 'Displacement', category: 'Distort',
    description: 'Animated noise-based UV displacement',
    previewCSS: 'repeating-conic-gradient(#888 0%, #aaa 10%, #888 20%)' },
  { type: 'twirl', label: 'Twirl', category: 'Distort',
    description: 'Rotational twirl distortion from center',
    previewCSS: 'conic-gradient(from 0deg at center, #888, #ccc, #888, #ccc, #888, #ccc)' },
  { type: 'pinchBulge', label: 'Pinch / Bulge', category: 'Distort',
    description: 'Pinch inward or bulge outward from center',
    previewCSS: 'radial-gradient(circle at center, #fff 10%, #aaa 30%, #666 60%, #333 100%)' },
  { type: 'polarTransform', label: 'Polar Transform', category: 'Distort',
    description: 'Cartesian to polar coordinate warp — wrap to circle',
    previewCSS: 'conic-gradient(from 0deg, #864, #486, #648, #864)' },
  { type: 'timeSmear', label: 'Time Smear', category: 'Distort',
    description: 'Directional paint smear with moveable line position. Horizontal, vertical, radial, or rotational modes.',
    previewCSS: 'linear-gradient(90deg, #a86 0%, #fff3 30%, #fff0 50%, #fff3 70%, #68a 100%)' },

  // ── Keying (5) ──
  { type: 'chromaKey', label: 'Chroma Key', category: 'Keying',
    description: 'Green/blue screen color removal',
    previewCSS: 'linear-gradient(135deg, #0f0 0%, #0f0 50%, transparent 50%)' },
  { type: 'lumaKey', label: 'Luma Key', category: 'Keying',
    description: 'Remove pixels by brightness threshold',
    previewCSS: 'linear-gradient(135deg, #000 0%, #000 50%, transparent 50%)' },
  { type: 'differenceKey', label: 'Difference Key', category: 'Keying',
    description: 'Key based on color difference from reference',
    previewCSS: 'linear-gradient(135deg, #888 0%, transparent 60%)' },
  { type: 'erode', label: 'Erode Matte', category: 'Keying',
    description: 'Shrink alpha matte edges',
    previewCSS: 'radial-gradient(circle at center, #fff 30%, #888 50%, #000 60%)' },
  { type: 'dilate', label: 'Dilate Matte', category: 'Keying',
    description: 'Expand alpha matte edges',
    previewCSS: 'radial-gradient(circle at center, #fff 40%, #ccc 55%, #000 70%)' },

  // ── Advanced Color (3) ──
  { type: 'falseColor', label: 'False Color', category: 'Advanced Color',
    description: 'IRE exposure zebra — visualize under/overexposure',
    previewCSS: 'linear-gradient(90deg, #a0f 0%, #00f 16%, #0af 33%, #0f0 50%, #ff0 66%, #f80 83%, #f00 100%)' },
  { type: 'shadowRecovery', label: 'Shadow Recovery', category: 'Advanced Color',
    description: 'Lift shadow detail without blowing highlights',
    previewCSS: 'linear-gradient(135deg, #666 0%, #999 30%, #aaa 50%, #bbb 100%)' },
  { type: 'highlightRolloff', label: 'Highlight Roll-off', category: 'Advanced Color',
    description: 'Soft-clip highlights with cinematic shoulder',
    previewCSS: 'linear-gradient(135deg, #888 0%, #bbb 40%, #ddd 60%, #eee 80%, #eee 100%)' },

  // ── Advanced Stylize (6) ──
  { type: 'compressionArtifacts', label: 'Compression Artifacts', category: 'Advanced Stylize',
    description: 'JPEG-style block compression artifacts',
    previewCSS: 'repeating-conic-gradient(#888 0% 25%, #999 25% 50%) 0 0/16px 16px' },
  { type: 'ascii', label: 'ASCII', category: 'Advanced Stylize',
    description: 'Convert image to ASCII character art',
    previewCSS: 'repeating-linear-gradient(90deg, #0f0 0px, #0f0 6px, #000 6px, #000 8px), repeating-linear-gradient(180deg, transparent 0px, transparent 8px, #010 8px, #010 10px), #000' },
  { type: 'comicInk', label: 'Comic Ink', category: 'Advanced Stylize',
    description: 'Comic book ink lines with halftone shading',
    previewCSS: 'radial-gradient(circle, #000 20%, #fff 21%) 0 0/8px 8px, linear-gradient(135deg, #000 0%, #000 45%, #fff 45.5%, #fff 55%, #000 55.5%)' },
  { type: 'datamoshLite', label: 'Datamosh', category: 'Advanced Stylize',
    description: 'Pixel sorting / datamosh digital glitch',
    previewCSS: 'linear-gradient(0deg, #f44 0%, #888 5%, #4f4 5%, #888 15%, #44f 15%, #888 20%, #888 100%)' },
  { type: 'scanlineDrift', label: 'Scanline Drift', category: 'Advanced Stylize',
    description: 'Animated scanline bands that drift and offset',
    previewCSS: 'repeating-linear-gradient(180deg, #888 0px, #888 4px, #bbb 4px, #bbb 6px, #666 6px, #666 10px)' },
  { type: 'tapeDropout', label: 'Tape Dropout', category: 'Advanced Stylize',
    description: 'VHS tape dropout — horizontal band loss with noise',
    previewCSS: 'linear-gradient(180deg, #888 0%, #888 30%, #fff 31%, #000 33%, #888 34%, #888 70%, #ccc 71%, #444 73%, #888 74%)' },

  // ── Advanced Warp (7) — consolidated; previously split with feedbackZoom dangling ──
  { type: 'rippleCaustics', label: 'Ripple Caustics', category: 'Advanced Warp',
    description: 'Animated underwater caustic light patterns',
    previewCSS: 'radial-gradient(circle at 30% 40%, rgba(100,200,255,0.4) 5%, transparent 20%), radial-gradient(circle at 70% 60%, rgba(100,200,255,0.3) 8%, transparent 25%), radial-gradient(circle at 50% 30%, rgba(150,220,255,0.2) 10%, transparent 30%), #446' },
  { type: 'shockwave', label: 'Shockwave', category: 'Advanced Warp',
    description: 'Expanding ring shockwave distortion',
    previewCSS: 'radial-gradient(circle at center, transparent 25%, rgba(255,255,255,0.5) 28%, transparent 32%, transparent 100%), #666' },
  { type: 'drosteRecursive', label: 'Droste Recursive', category: 'Advanced Warp',
    description: 'Recursive spiral zoom — Escher-style infinite mirror',
    previewCSS: 'repeating-radial-gradient(circle at center, #888 0px, #ccc 10px, #888 20px)' },
  { type: 'slitScan', label: 'Slit-Scan', category: 'Advanced Warp',
    description: 'Temporal slit-scan — each row samples different time',
    previewCSS: 'repeating-linear-gradient(180deg, #a86 0px, #68a 5px, #86a 10px, #a68 15px)' },
  { type: 'fractalWarp', label: 'Fractal Warp', category: 'Advanced Warp',
    description: 'Mandelbrot/Julia fractal with image colors mapped to iteration depth',
    previewCSS: 'radial-gradient(ellipse at 30% 50%, #000 0%, #206 20%, #40c 40%, #f80 60%, #ff0 80%, #fff 100%)' },
  { type: 'fluidDistort', label: 'Fluid Distort', category: 'Advanced Warp',
    description: 'Iterative fluid advection — organic smoke and liquid warping',
    previewCSS: 'radial-gradient(ellipse at 60% 40%, #0af 0%, #04a 40%, #000 70%)' },
  { type: 'wormhole', label: 'Wormhole', category: 'Advanced Warp',
    description: 'Gravitational lensing around a singularity with Einstein ring and accretion disk',
    previewCSS: 'radial-gradient(circle, #000 0%, #f80 15%, #fa0 20%, #000 30%, #224 60%, #000 100%)' },

  // ── Advanced Atmosphere (5) ──
  { type: 'volumetricFogOverlay', label: 'Volumetric Fog', category: 'Advanced Atmosphere',
    description: 'Animated layered perlin noise fog overlay',
    previewCSS: 'linear-gradient(180deg, transparent 0%, rgba(180,190,210,0.2) 30%, rgba(160,170,190,0.5) 60%, rgba(140,150,170,0.7) 100%)' },
  { type: 'rainFogSnowOverlay', label: 'Rain / Snow', category: 'Advanced Atmosphere',
    description: 'Animated particle weather — rain drops or snowflakes',
    previewCSS: 'radial-gradient(circle at 20% 10%, #fff 1px, transparent 2px), radial-gradient(circle at 50% 30%, #fff 1px, transparent 2px), radial-gradient(circle at 80% 20%, #fff 1px, transparent 2px), radial-gradient(circle at 35% 60%, #fff 1px, transparent 2px), radial-gradient(circle at 65% 80%, #fff 1px, transparent 2px), #446' },
  { type: 'particleOverlayFx', label: '3D Particles', category: 'Advanced Atmosphere',
    description: 'Dissolve image into lit 3D particles with depth and scatter',
    previewCSS: 'radial-gradient(circle at 20% 30%, #fa0 3px, transparent 5px), radial-gradient(circle at 55% 20%, #0af 4px, transparent 6px), radial-gradient(circle at 80% 60%, #f0a 3px, transparent 5px), radial-gradient(circle at 35% 70%, #af0 2px, transparent 4px), radial-gradient(circle at 65% 45%, #fff 2px, transparent 3px), #111' },
  { type: 'glintStarburst', label: 'Glint / Starburst', category: 'Advanced Atmosphere',
    description: '6-point star diffraction spikes on bright areas',
    previewCSS: 'conic-gradient(from 0deg at 50% 50%, transparent 0deg, rgba(255,255,255,0.8) 2deg, transparent 4deg, transparent 56deg, rgba(255,255,255,0.8) 58deg, transparent 60deg, transparent 116deg, rgba(255,255,255,0.6) 118deg, transparent 120deg, transparent 176deg, rgba(255,255,255,0.6) 178deg, transparent 180deg, transparent 236deg, rgba(255,255,255,0.5) 238deg, transparent 240deg, transparent 296deg, rgba(255,255,255,0.5) 298deg, transparent 300deg), #332' },
  { type: 'embossRelight', label: 'Emboss Relight', category: 'Advanced Atmosphere',
    description: 'Directional emboss with colored lighting',
    previewCSS: 'linear-gradient(135deg, #669 0%, #99c 50%, #446 100%)' },

  // ── Advanced Text & Pattern (16) — renamed from "Advanced Text" ──
  { type: 'dotMatrix', label: 'Dot Matrix', category: 'Advanced Text & Pattern',
    description: 'Circular dots of varying size based on luminance',
    previewCSS: 'radial-gradient(circle at 25% 25%, #fff 2px, transparent 3px), radial-gradient(circle at 75% 75%, #fff 4px, transparent 5px), radial-gradient(circle at 25% 75%, #fff 3px, transparent 4px), radial-gradient(circle at 75% 25%, #fff 1px, transparent 2px), #111' },
  { type: 'matrixRain', label: 'Matrix Rain', category: 'Advanced Text & Pattern',
    description: 'Falling green character columns like The Matrix',
    previewCSS: 'linear-gradient(180deg, #000 0%, #0a3 30%, #0f6 50%, #0a3 70%, #000 100%)' },
  { type: 'binaryCode', label: 'Binary Code', category: 'Advanced Text & Pattern',
    description: 'Render image as 0s and 1s grid',
    previewCSS: 'linear-gradient(90deg, #0a0 0%, #000 20%, #0f0 40%, #000 60%, #0a0 80%, #000 100%)' },
  { type: 'crosshatch', label: 'Crosshatch', category: 'Advanced Text & Pattern',
    description: 'Pen-and-ink crosshatch shading',
    previewCSS: 'repeating-linear-gradient(45deg, transparent, transparent 3px, #ccc 3px, #ccc 4px), repeating-linear-gradient(-45deg, transparent, transparent 3px, #999 3px, #999 4px), #222' },
  { type: 'blockMosaic', label: 'Block Mosaic', category: 'Advanced Text & Pattern',
    description: 'Unicode-style block element rendering (light/medium/dark/full)',
    previewCSS: 'linear-gradient(90deg, #333 0%, #333 25%, #666 25%, #666 50%, #999 50%, #999 75%, #fff 75%)' },
  { type: 'numberGrid', label: 'Number Grid', category: 'Advanced Text & Pattern',
    description: 'Map luminance to 0-9 digit density patterns',
    previewCSS: 'linear-gradient(135deg, #f80 0%, #fa0 30%, #000 50%, #0af 70%, #08f 100%)' },
  { type: 'braillePattern', label: 'Braille Pattern', category: 'Advanced Text & Pattern',
    description: 'Braille-like 2x4 dot grids where luminance activates dots',
    previewCSS: 'radial-gradient(circle at 30% 20%, #fff 1px, transparent 2px), radial-gradient(circle at 30% 40%, #fff 1px, transparent 2px), radial-gradient(circle at 30% 60%, #fff 1px, transparent 2px), radial-gradient(circle at 70% 80%, #fff 1px, transparent 2px), #111' },
  { type: 'circuitBoard', label: 'Circuit Board', category: 'Advanced Text & Pattern',
    description: 'PCB-style traces and connection nodes from image luminance',
    previewCSS: 'linear-gradient(0deg, #0a3 0%, transparent 1px), linear-gradient(90deg, #0a3 0%, transparent 1px), #051' },
  { type: 'stainedGlass', label: 'Stained Glass', category: 'Advanced Text & Pattern',
    description: 'Voronoi cell tessellation with dark lead borders',
    previewCSS: 'conic-gradient(from 0deg at 30% 40%, #f44, #4f4, #44f, #ff4, #f44), #222' },
  { type: 'wovenFabric', label: 'Woven Fabric', category: 'Advanced Text & Pattern',
    description: 'Interlocking warp and weft threads colored by source',
    previewCSS: 'repeating-linear-gradient(0deg, #864 0px, #864 2px, transparent 2px, transparent 4px), repeating-linear-gradient(90deg, #648 0px, #648 2px, transparent 2px, transparent 4px), #432' },
  { type: 'mosaicTile', label: 'Mosaic Tile', category: 'Advanced Text & Pattern',
    description: 'Irregular shaped tiles with grout lines and random rotation',
    previewCSS: 'repeating-conic-gradient(from 0deg at 50% 50%, #a86 0deg 90deg, #8a6 90deg 180deg, #68a 180deg 270deg, #86a 270deg 360deg), #333' },
  { type: 'neonOutline', label: 'Neon Outline', category: 'Advanced Text & Pattern',
    description: 'Glowing neon edge detection with bloom glow',
    previewCSS: 'radial-gradient(circle at 50% 50%, #f0f8 0%, transparent 40%), linear-gradient(45deg, #000 0%, #111 100%)' },
  { type: 'pixelSort', label: 'Pixel Sort', category: 'Advanced Text & Pattern',
    description: 'Luminance-based pixel sorting with vertical streak artifacts',
    previewCSS: 'linear-gradient(180deg, #000 0%, #444 20%, #fff 40%, #888 60%, #222 80%, #000 100%)' },
  { type: 'linocut', label: 'Linocut', category: 'Advanced Text & Pattern',
    description: 'Woodcut print aesthetic with carved relief grooves',
    previewCSS: 'repeating-linear-gradient(135deg, #f5f0e8 0px, #f5f0e8 2px, #1a1a1a 2px, #1a1a1a 3px), #f5f0e8' },
  { type: 'topoMap', label: 'Topo Map', category: 'Advanced Text & Pattern',
    description: 'Topographic contour map lines at luminance elevation intervals',
    previewCSS: 'repeating-radial-gradient(circle at 40% 50%, #4a3 0px, #4a3 1px, #8c6 1px, #8c6 8px), #6b5' },
  { type: 'ledWall', label: 'LED Wall', category: 'Advanced Text & Pattern',
    description: 'LED display wall with visible RGB sub-pixel elements and bloom',
    previewCSS: 'radial-gradient(circle at 25% 50%, #f00 0%, transparent 30%), radial-gradient(circle at 50% 50%, #0f0 0%, transparent 30%), radial-gradient(circle at 75% 50%, #00f 0%, transparent 30%), #111' },

  // ── Advanced 3D (19) ──
  { type: 'explode3D', label: 'Explode 3D', category: 'Advanced 3D',
    description: 'Dissolve image into 3D particles forming sphere, cube, pyramid, torus and more',
    previewCSS: 'radial-gradient(circle at 50% 50%, #f80 0%, #f40 30%, #000 60%, #222 100%)' },
  { type: 'terrain3D', label: 'Terrain', category: 'Advanced 3D',
    description: 'Raymarched heightmap terrain from image luminance with fly-over camera. Now supports horizon-fade-to-transparent and source-blend modes.',
    previewCSS: 'linear-gradient(180deg, #48f 0%, #8af 25%, #4a3 50%, #362 75%, #241 100%)' },
  { type: 'wrappedTerrain', label: 'Wrapped Terrain', category: 'Advanced 3D',
    description: 'Source image extruded as luma displacement around a sphere, cube, or pyramid. Auto-rotate + Fresnel silhouette fade + tile scale.',
    previewCSS: 'radial-gradient(circle at 30% 30%, #fc4 0%, #f80 30%, #f04 60%, transparent 80%), radial-gradient(circle at 70% 70%, #08f 0%, #04a 30%, transparent 50%), #112' },

  // ── Geometric 3D (10) ──
  { type: 'stringOrb', label: 'String Orb', category: 'Geometric 3D',
    description: 'Wire-wrapped luminous globe sampling source along latitude + longitude + diagonal strings with rim glow + audio hooks.',
    previewCSS: 'radial-gradient(circle, #4cf 5%, transparent 25%), radial-gradient(circle, transparent 60%, #4cf8 75%, transparent 80%), repeating-linear-gradient(0deg, transparent 0px, transparent 8px, #4cf6 8px, #4cf6 9px), repeating-linear-gradient(90deg, transparent 0px, transparent 8px, #4cf6 8px, #4cf6 9px), #001' },
  { type: 'sphereWireframe', label: 'Sphere Wireframe', category: 'Geometric 3D',
    description: 'Geodesic globe with meridian + parallel wireframe lines, halo glow, and optional source fill of faces.',
    previewCSS: 'radial-gradient(circle, transparent 60%, #6cf6 75%, transparent 80%), repeating-conic-gradient(from 0deg, transparent 0deg, transparent 25deg, #6cf6 25deg, #6cf6 27deg), #002' },
  { type: 'voxelCubeCluster', label: 'Voxel Cube Cluster', category: 'Geometric 3D',
    description: 'Floating array of cubes (up to 8×8×8) with per-cube luma extrusion. Each face shows a source patch.',
    previewCSS: 'linear-gradient(45deg, #f80 25%, transparent 25%, transparent 75%, #f80 75%) 0 0 / 30px 30px, linear-gradient(45deg, #08f 25%, transparent 25%, transparent 75%, #08f 75%) 15px 15px / 30px 30px, #112' },
  { type: 'mobiusLattice', label: 'Mobius Lattice', category: 'Geometric 3D',
    description: 'Twisted ribbon mosaic with parametric Möbius surface + lattice line overlay that loops on itself.',
    previewCSS: 'conic-gradient(from 45deg at 50% 50%, #fc4 0%, #f80 25%, #f08 50%, #80f 75%, #fc4 100%)' },
  { type: 'crystalShardField', label: 'Crystal Shard Field', category: 'Geometric 3D',
    description: 'SDF cluster of randomly oriented refractive prisms. Chromatic edges + specular highlights.',
    previewCSS: 'linear-gradient(60deg, #fff8 0%, transparent 30%), linear-gradient(120deg, #cef8 30%, transparent 60%), linear-gradient(0deg, #efc8 60%, transparent 90%), #224' },
  { type: 'tubeLattice', label: 'Tube Lattice', category: 'Geometric 3D',
    description: 'Cylinder grid with source mapped to barrel UV. Audio bass thickens tubes; spiral twist over time.',
    previewCSS: 'repeating-linear-gradient(0deg, #0fc 0px, #0fc 4px, transparent 4px, transparent 18px), #013' },
  { type: 'discoMirrorBall', label: 'Disco Mirror Ball', category: 'Geometric 3D',
    description: 'Faceted ball with chase lights + sparkle on bass. Quantized facet UV with rainbow hue cycle.',
    previewCSS: 'radial-gradient(circle at 30% 30%, #fff 0%, #ff8 15%, transparent 30%), conic-gradient(from 0deg at 50% 50%, #f08, #80f, #08f, #0fc, #fc0, #f80, #f08), #112' },
  { type: 'lissajousKnot', label: 'Lissajous Knot', category: 'Geometric 3D',
    description: 'Animated tubular swept frame around a 3D Lissajous curve. Configurable XYZ ratios + phases.',
    previewCSS: 'radial-gradient(ellipse at 50% 50%, transparent 30%, #f0c8 35%, #80f8 50%, #08f8 65%, transparent 80%), #001' },
  { type: 'helixParticleStream', label: 'Helix Particle Stream', category: 'Geometric 3D',
    description: 'Multiple helical curves rising over time like a DNA double-helix made of source pixels.',
    previewCSS: 'linear-gradient(180deg, transparent 0%, #4f8 50%, #4f8 50%, transparent 100%), repeating-linear-gradient(0deg, transparent 0px, transparent 8px, #4f88 8px, #4f88 12px), #021' },
  { type: 'donutConstellation', label: 'Donut Constellation', category: 'Geometric 3D',
    description: 'Glowing torus with audio-pulsed star nodes circling the major radius. Configurable star count + pulse.',
    previewCSS: 'radial-gradient(ellipse 80% 30% at 50% 50%, #c4f 0%, #80f 40%, transparent 60%), radial-gradient(circle at 25% 50%, #fff 0%, transparent 5%), radial-gradient(circle at 75% 50%, #fff 0%, transparent 5%), #001' },
  { type: 'sphereProject', label: 'Sphere Projection', category: 'Advanced 3D',
    description: 'Project image onto a rotating lit 3D sphere with Fresnel rim glow',
    previewCSS: 'radial-gradient(circle at 40% 40%, #fff 0%, #88f 30%, #228 60%, #000 100%)' },
  { type: 'cubeProject', label: 'Cube Projection', category: 'Advanced 3D',
    description: 'Wrap image onto faces of a rotating 3D cube with edge glow',
    previewCSS: 'linear-gradient(135deg, #444 0%, #888 25%, #aaa 50%, #666 75%, #333 100%)' },
  { type: 'cylinderWrap', label: 'Cylinder Wrap', category: 'Advanced 3D',
    description: 'Wrap image around a rotating 3D cylinder with perspective and lighting',
    previewCSS: 'linear-gradient(90deg, #222 0%, #888 30%, #fff 50%, #888 70%, #222 100%)' },
  { type: 'torusTunnel', label: 'Torus Tunnel', category: 'Advanced 3D',
    description: 'Fly through a torus donut hole with texture mapped on the inner surface',
    previewCSS: 'radial-gradient(ellipse at 50% 50%, #000 0%, #448 40%, #88f 60%, #000 100%)' },
  { type: 'diamondGem', label: 'Diamond Gem', category: 'Advanced 3D',
    description: 'Faceted diamond with refraction highlights, rainbow dispersion, and sparkle',
    previewCSS: 'conic-gradient(from 0deg, #f0f, #0ff, #ff0, #0f0, #f0f)' },
  { type: 'shatter3D', label: 'Shatter', category: 'Advanced 3D',
    description: 'Image fractures into triangular shards that explode outward and reassemble',
    previewCSS: 'linear-gradient(45deg, #333 25%, transparent 25%, transparent 75%, #333 75%)' },
  { type: 'mobiusStrip', label: 'Möbius Strip', category: 'Advanced 3D',
    description: 'Texture mapped onto a twisted Möbius band with configurable twist count',
    previewCSS: 'linear-gradient(135deg, #648 0%, #86c 30%, #a8e 50%, #86c 70%, #648 100%)' },
  { type: 'voxelDisplace', label: 'Voxel Displace', category: 'Advanced 3D',
    description: 'Convert image to 3D voxel grid where brightness drives cube height',
    previewCSS: 'repeating-linear-gradient(90deg, #4a4 0px, #4a4 4px, #000 4px, #000 6px)' },
  { type: 'waveSurface', label: 'Wave Surface', category: 'Advanced 3D',
    description: 'Image stretched across animated ocean waves with specular lighting',
    previewCSS: 'linear-gradient(180deg, #48f 0%, #28a 30%, #4af 50%, #268 70%, #124 100%)' },
  { type: 'prismSplit', label: 'Prism Split', category: 'Advanced 3D',
    description: 'RGB chromatic dispersion through a triangular prism with rainbow caustics',
    previewCSS: 'linear-gradient(120deg, #f00 0%, #ff0 20%, #0f0 40%, #0ff 60%, #00f 80%, #f0f 100%)' },
  { type: 'origamiFold', label: 'Origami Fold', category: 'Advanced 3D',
    description: 'Paper-fold creases across the image with 3D depth shading and animation',
    previewCSS: 'repeating-linear-gradient(90deg, #ddd 0px, #fff 10px, #aaa 20px)' },
  { type: 'mirrorRoom', label: 'Infinite Mirror Room', category: 'Advanced 3D',
    description: 'Image on walls of a mirrored box with infinite reflections receding into depth',
    previewCSS: 'repeating-radial-gradient(circle, #88f 0px, #448 20px, #226 40px)' },
  { type: 'geometricTile', label: 'Geometric Tile', category: 'Advanced 3D',
    description: 'Image tiles independently rotate in 3D like a flip-board display',
    previewCSS: 'repeating-conic-gradient(from 0deg, #555 0deg 90deg, #333 90deg 180deg)' },
  { type: 'geometricTilePro', label: 'Geometric Tile Pro', category: 'Advanced 3D',
    description: 'Flip-board grid: every tile independently rotates in 3D with perspective + per-tile lighting + gap borders',
    previewCSS: 'linear-gradient(135deg, #FF6B6B 0%, #555 30%, #222 60%, #FF6B6B 90%)' },
  { type: 'hexGrid', label: 'Hex Grid', category: 'Advanced 3D',
    description: 'Honeycomb hexagonal tiles that pop and rotate with animated depth lighting',
    previewCSS: 'conic-gradient(from 30deg, #556 0deg, #889 60deg, #556 120deg, #889 180deg, #556 240deg, #889 300deg, #556 360deg)' },
  { type: 'spiralTile', label: 'Spiral Tiles', category: 'Advanced 3D',
    description: 'Logarithmic spiral sectors with animated spin and flip effects',
    previewCSS: 'conic-gradient(from 0deg, #a66 0deg, #6a6 120deg, #66a 240deg, #a66 360deg)' },
  { type: 'shingleStack', label: 'Shingle Stack', category: 'Advanced 3D',
    description: 'Overlapping brick-pattern tiles with parallax depth like roof shingles',
    previewCSS: 'repeating-linear-gradient(0deg, #765 0px, #987 8px, #654 16px)' },
  { type: 'voronoiShatter', label: 'Voronoi Shatter', category: 'Advanced 3D',
    description: 'Organic cell-based fragmentation with drifting edges and depth lighting',
    previewCSS: 'radial-gradient(circle at 30% 40%, #889 0%, #445 30%, #667 50%, #334 80%)' },

  // ── Advanced Depth (3) ──
  { type: 'tunnelFlight', label: 'Tunnel Flight', category: 'Advanced Depth',
    description: 'Infinite textured tunnel — fly through with morphing cross-section and fog',
    previewCSS: 'radial-gradient(circle, #000 0%, #306 40%, #609 70%, #000 100%)' },
  { type: 'infiniteMirror', label: 'Infinite Mirror', category: 'Advanced Depth',
    description: 'Recursive mirror room with chromatic reflections fading into infinity',
    previewCSS: 'repeating-linear-gradient(90deg, #446 0px, #668 4px, #224 8px)' },
  { type: 'crystalRefract', label: 'Crystal Refract', category: 'Advanced Depth',
    description: 'Raymarched crystal gem refracting image with chromatic dispersion',
    previewCSS: 'linear-gradient(135deg, #f0f8 0%, #0ff8 33%, #ff08 66%, #f0f8 100%), #111' },

  // ── Advanced Feedback (1) ──
  { type: 'feedbackZoom', label: 'Feedback Zoom', category: 'Advanced Feedback',
    description: 'Simulated video feedback — iterative zoom + rotate creates hypnotic spiral trails',
    previewCSS: 'repeating-radial-gradient(circle, #f80 0px, #000 8px, #80f 16px, #000 24px)' },

  // ── Advanced Trails (7) ──
  { type: 'motionTrails', label: 'Motion Trails', category: 'Advanced Trails',
    description: 'Long-exposure light trail streaks from bright pixels',
    previewCSS: 'linear-gradient(0deg, transparent 0%, #f804 20%, #fa06 50%, #f808 80%, transparent 100%), #111' },
  { type: 'echoRepeat', label: 'Echo Repeat', category: 'Advanced Trails',
    description: 'Multiple offset copies with progressive fade — visual delay/echo',
    previewCSS: 'linear-gradient(135deg, #fff8 0%, #fff4 25%, #fff2 50%, #fff1 75%, transparent 100%), #222' },
  { type: 'ghostDouble', label: 'Ghost Double', category: 'Advanced Trails',
    description: 'Phase-shifted ghost copies with chromatic shift — spirit photography look',
    previewCSS: 'linear-gradient(90deg, #f008 0%, #0f04 33%, #00f8 66%, transparent 100%), #222' },
  { type: 'strobeFlash', label: 'Strobe Flash', category: 'Advanced Trails',
    description: 'Rhythmic flash/pulse — white, black, invert, or color strobe modes',
    previewCSS: 'repeating-linear-gradient(90deg, #fff 0px, #fff 4px, #000 4px, #000 8px)' },
  { type: 'lightPaint', label: 'Light Paint', category: 'Advanced Trails',
    description: 'Light painting — bright pixels leave luminance trails along flow paths',
    previewCSS: 'radial-gradient(ellipse at 30% 60%, #ff0 0%, #f80 20%, #f04 40%, transparent 60%), #111' },
  { type: 'recursiveEcho', label: 'Recursive Echo', category: 'Advanced Trails',
    description: 'Cascading echo corridor — iterative translate + scale with color shift',
    previewCSS: 'linear-gradient(45deg, #80f8 0%, #80f4 25%, #80f2 50%, #80f1 75%, transparent 100%), #111' },
  { type: 'chronophoto', label: 'Chronophotography', category: 'Advanced Trails',
    description: 'Stroboscopic multi-exposure trail effect. Linear, circular, zoom, and spiral echo trails.',
    previewCSS: 'repeating-linear-gradient(45deg, #fff4 0px, #fff0 8px, #fff4 16px), #446' },

  // ── New Hero Effects (Batch A) ──
  { type: 'opticalFlowDatamosh', label: 'Optical Flow Datamosh', category: 'New Hero',
    description: 'Frame-difference motion-vector estimation displaces the previous frame. Normal/glitch/smooth modes with freeze + chroma split.',
    previewCSS: 'linear-gradient(120deg, #f08 0%, #80f 30%, #08f 60%, #0fc 100%)' },
  { type: 'flowFieldTrails', label: 'Flow Field Trails', category: 'New Hero',
    description: 'UV streaks marched along an animated curl-noise vector field. Advect / streak / tendril modes + hue cycle.',
    previewCSS: 'radial-gradient(ellipse at 30% 60%, #f80 0%, #f08 30%, #80f 60%, #08f 90%)' },
  { type: 'reactionDiffusion', label: 'Reaction Diffusion', category: 'New Hero',
    description: 'Gray-Scott pattern simulation grown over the source. Spots / stripes / mitosis / coral patterns, masked by luma.',
    previewCSS: 'radial-gradient(circle, #fff 5%, #233 20%, #fff 30%, #233 45%, #fff 55%, #233 70%)' },
  { type: 'neonTubeTrace', label: 'Neon Tube Trace', category: 'New Hero',
    description: 'Detect edges and convert to glowing animated neon tubes with marching chase + flicker.',
    previewCSS: 'linear-gradient(90deg, #f08c 0%, #08fc 50%, #0fcc 100%), #000' },
  { type: 'depthParallax', label: 'Depth Parallax (Fake)', category: 'New Hero',
    description: 'Estimate depth from luma → render multiple parallax layers. Push / pan / swing modes with chromatic depth.',
    previewCSS: 'linear-gradient(180deg, #035 0%, #069 30%, #2af 60%, #cef 100%)' },
  { type: 'pointCloudDissolve', label: 'Point Cloud Dissolve', category: 'New Hero',
    description: 'Image becomes scattered dots with attract / scatter / reform animation. Square / circle / cross dot shapes.',
    previewCSS: 'radial-gradient(circle, #fff 1px, transparent 2px), radial-gradient(circle at 33% 50%, #fff 1px, transparent 2px), #111' },
  { type: 'pixelSand', label: 'Pixel Sand', category: 'New Hero',
    description: 'Bright pixels fall like sand under gravity + turbulence. Fall / rise / swirl directions, persistence + replenish.',
    previewCSS: 'linear-gradient(180deg, transparent 0%, #ffe8b0 50%, #f8c860 100%), #210' },
  { type: 'liquidGlass', label: 'Liquid Glass', category: 'New Hero',
    description: 'Refractive blob lens with chromatic caustics + specular highlights. Up to 8 animated blobs with tint.',
    previewCSS: 'radial-gradient(ellipse at 30% 30%, #fff8 0%, #fff2 25%, transparent 50%), radial-gradient(ellipse at 70% 70%, #fff6 0%, transparent 40%), #44a' },
  { type: 'hologramScan', label: 'Hologram Scan', category: 'New Hero',
    description: 'Sci-fi hologram look: projector grid + descending scan beam + RGB flicker + broken bands + edge glow.',
    previewCSS: 'repeating-linear-gradient(0deg, #0fc8 0px, #0fc4 1px, transparent 2px, transparent 6px), #013' },
  { type: 'laserSlice', label: 'Laser Slice', category: 'New Hero',
    description: 'Moving scan plane reveals or erases image with glow + sparks. Horizontal / vertical / diagonal / radial.',
    previewCSS: 'linear-gradient(90deg, #f00 0%, #f44 5%, transparent 8%), linear-gradient(90deg, transparent 92%, #f44 95%, #f00 100%), #111' },

  // ── New Hero Effects (Batch B) ──
  { type: 'auraField', label: 'Aura Field', category: 'New Hero',
    description: 'Soft color fields bloom from edges + audio peaks with hue cycling and add/screen/replace blends.',
    previewCSS: 'radial-gradient(ellipse at 30% 50%, #0fcc 0%, transparent 40%), radial-gradient(ellipse at 70% 50%, #f0cc 0%, transparent 40%), #112' },
  { type: 'smokeDisintegrate', label: 'Smoke Disintegrate', category: 'New Hero',
    description: 'Animated smoke wisps dissolve the image. Top-down / center-out / fbm-driven directions with wind angle.',
    previewCSS: 'linear-gradient(180deg, #fff8 0%, #fff4 30%, transparent 60%), radial-gradient(ellipse at 50% 30%, #fff6 0%, transparent 50%), #222' },
  { type: 'shimmerCloth', label: 'Shimmer Cloth', category: 'New Hero',
    description: 'Image becomes waving fabric with thread weave (horizontal / plaid / satin) + silk shimmer highlights.',
    previewCSS: 'repeating-linear-gradient(45deg, #c98 0px, #c98 2px, #a76 2px, #a76 4px), #874' },
  { type: 'glitchQuilt', label: 'Glitch Quilt', category: 'New Hero',
    description: 'Tiles reorder, rotate, and delay independently. Quilt / swap / mosh modes with feedback-driven delay.',
    previewCSS: 'conic-gradient(from 45deg at 25% 25%, #f08, #80f, #08f, #0f8), conic-gradient(from 90deg at 75% 75%, #fc0, #f80, #f08, #80f), #222' },
  { type: 'cellularAutomataBurn', label: 'Cellular Automata Burn', category: 'New Hero',
    description: 'Game-of-life cells spread through bright regions. Conway / Brian\'s Brain / Burn rules with custom thresholds.',
    previewCSS: 'radial-gradient(circle at 30% 30%, #f80 0px, #f80 2px, transparent 3px), radial-gradient(circle at 60% 50%, #f08 0px, #f08 2px, transparent 3px), radial-gradient(circle at 80% 70%, #fc0 0px, #fc0 2px, transparent 3px), #211' },
  { type: 'rorschachMirror', label: 'Rorschach Mirror', category: 'New Hero',
    description: 'Bilateral ink symmetry with animated fluid edges. Vertical / horizontal / both / 4-fold mirror modes.',
    previewCSS: 'radial-gradient(ellipse at 25% 50%, #111 0%, transparent 35%), radial-gradient(ellipse at 75% 50%, #111 0%, transparent 35%), #f5f4ed' },
  { type: 'spectralPrismTunnel', label: 'Spectral Prism Tunnel', category: 'New Hero',
    description: 'Refracts the image into recursive rainbow tunnel slices with depth fade and rotation.',
    previewCSS: 'radial-gradient(circle at 50% 50%, #f00 0%, #ff0 20%, #0f0 40%, #0ff 60%, #00f 80%, #f0f 100%)' },
  { type: 'ledVolume', label: 'LED Volume', category: 'New Hero',
    description: 'Image mapped to 3D LED voxel wall with depth pulse, glow, and perspective. Square / round / hex voxels.',
    previewCSS: 'radial-gradient(circle at 25% 25%, #f00 0px, #f00 4px, transparent 5px), radial-gradient(circle at 75% 50%, #0f0 0px, #0f0 4px, transparent 5px), radial-gradient(circle at 50% 75%, #00f 0px, #00f 4px, transparent 5px), #000' },
  { type: 'posterTear', label: 'Poster Tear', category: 'New Hero',
    description: 'Paper-rip mask reveals duplicated/offset layers beneath. Line / arc / rectangle tear shapes with edge glow.',
    previewCSS: 'linear-gradient(135deg, #fcb 50%, transparent 50%), linear-gradient(45deg, #c98 50%, transparent 50%), #555' },
  { type: 'paintPeel', label: 'Paint Peel', category: 'New Hero',
    description: 'Edges curl/flake away based on noise + luma. fBm / cellular / cracks patterns with curl shading.',
    previewCSS: 'radial-gradient(circle at 20% 30%, transparent 30%, #864 32%), radial-gradient(circle at 70% 60%, transparent 25%, #864 27%), #cba' },

  // ── New Hero Effects (Batch C) ──
  { type: 'audioShockBloom', label: 'Audio Shock Bloom', category: 'New Hero',
    description: 'Beat-triggered bloom + radial shockwave + chroma split + strobe. Reads audio for kick-driven pulse.',
    previewCSS: 'radial-gradient(circle, #fff 0%, #fc4 20%, #f08 40%, transparent 60%), radial-gradient(circle, transparent 50%, #80f4 65%, transparent 75%), #111' },
  { type: 'vhsFullDeck', label: 'VHS Full Deck', category: 'New Hero',
    description: 'All-in-one VHS: tracking + head switch + chroma bleed + dropouts + tape noise + scanlines + saturation.',
    previewCSS: 'repeating-linear-gradient(0deg, #444 0px, #555 1px, #444 2px), linear-gradient(180deg, transparent 80%, #fff8 95%, transparent 100%), #322' },
  { type: 'analogFeedbackRack', label: 'Analog Feedback Rack', category: 'New Hero',
    description: 'Real feedback buffer with zoom + rotate + decay + hue shift + center mask. Recursive frame accumulation.',
    previewCSS: 'conic-gradient(from 0deg, #f08 0%, #80f 25%, #08f 50%, #0fc 75%, #f08 100%)' },
  { type: 'clubLaserGrid', label: 'Club Laser Grid', category: 'New Hero',
    description: 'Perspective grid (floor / ceiling / tunnel) with audio-reactive scanlines and glowing intersections.',
    previewCSS: 'linear-gradient(180deg, transparent 0%, #0f8 100%), repeating-linear-gradient(90deg, transparent 0px, transparent 14px, #0f88 14px, #0f88 16px), #002' },
  { type: 'mirrorShards', label: 'Mirror Shards', category: 'New Hero',
    description: 'Kaleidoscopic shard field (voronoi / hex / triangular) with per-shard rotation and feedback delay.',
    previewCSS: 'conic-gradient(from 30deg at 30% 40%, #f08, #80f, #08f), conic-gradient(from 120deg at 70% 70%, #fc0, #f80, #f04)' },
  { type: 'ghostExposure', label: 'Ghost Exposure', category: 'New Hero',
    description: 'Long-exposure accumulation with configurable decay, hue shift per frame, and add/max/screen modes.',
    previewCSS: 'linear-gradient(135deg, #fffc 0%, #fff8 25%, #fff4 50%, #fff2 75%, transparent 100%), #112' },
  { type: 'thermalContour', label: 'Thermal Contour', category: 'New Hero',
    description: 'Thermal palette (Ironbow / Jet / Viridis / Inferno) plus contour isolines and bright-blob tracking.',
    previewCSS: 'linear-gradient(90deg, #002 0%, #80f 20%, #f80 50%, #ff4 75%, #fff 100%)' },
  { type: 'dreamDiffusion', label: 'Dream Diffusion Look', category: 'New Hero',
    description: 'Soft bloom + halation + chromatic blur + pastel highlight rolloff + shadow lift. Hazy dream-like grade.',
    previewCSS: 'radial-gradient(ellipse at 30% 50%, #ffeac8 0%, #fcd 35%, #cdf 80%), #fff' },
  { type: 'topoWarp', label: 'Topographic Depth Warp', category: 'New Hero',
    description: 'Luma-derived contour lines become physical displacement ridges with shadow + chromatic edge.',
    previewCSS: 'repeating-radial-gradient(circle at 50% 50%, #003 0px, #003 6px, #069 6px, #069 8px, #2af 8px, #2af 10px)' },
  { type: 'strobeSequencer', label: 'Strobe Sequencer', category: 'New Hero',
    description: 'BPM-synced strobe with editable 16-step pattern (bitmask). On/Off / Invert / Tint / Zoom modes + swing.',
    previewCSS: 'repeating-linear-gradient(90deg, #fff 0px, #fff 6px, #000 6px, #000 12px)' },
];

// Auto-derive tier from category for each effect
export const EFFECT_CATALOG: EffectCatalogEntry[] = RAW_CATALOG.map(entry => ({
  ...entry,
  tier: getEffectTier(entry.category),
}));

// Helper to get all unique categories in order
export function getEffectCategories(): string[] {
  const seen = new Set<string>();
  const cats: string[] = [];
  for (const entry of EFFECT_CATALOG) {
    if (!seen.has(entry.category)) {
      seen.add(entry.category);
      cats.push(entry.category);
    }
  }
  return cats;
}
