/** Public documentation routes. Keep these aligned with ghostarcade-web/docsNav. */
export const helpTopics: Record<string, { title: string; description: string }> = {
  interface: { title: 'Workspace controls', description: 'Arrange the workspace and choose the tools for your performance.' },
  'getting-started': { title: 'Getting started', description: 'Create your first project and choose a workspace.' },
  projects: { title: 'Projects and media', description: 'Save your show, reopen it, and manage the media it references.' },
  'projection-mapping': { title: 'Projection mapping', description: 'Align and warp content to match a physical surface.' },
  layers: { title: 'Layers and content', description: 'Choose content, adjust its appearance, and combine it with other layers.' },
  'masks-slices': { title: 'Masks and slices', description: 'Crop, mask and arrange regions of content in your output.' },
  'multi-output': { title: 'Output routing', description: 'Choose where the composition is displayed and configure its output.' },
  'stage-simulator': { title: 'Stage design', description: 'Arrange a stage and preview content on its screens.' },
  'projection-simulator': { title: 'Projection simulator', description: 'Preview projector placement and coverage before setting up at the venue.' },
  'vj-mode': { title: 'VJ performance', description: 'Mix live layers and blend between decks A and B.' },
  'clip-launcher': { title: 'Clip launcher', description: 'Load and launch clips, set their playback behavior, and sequence your layers.' },
  'macros-snapshots': { title: 'Macros and snapshots', description: 'Control multiple effect parameters with one knob or recall a saved look.' },
  'show-timeline': { title: 'Show timeline', description: 'Arrange changes over time for a structured performance.' },
  synthvision: { title: 'Performer mode', description: 'Play visuals from a focused performance surface.' },
  'gpu-instruments': { title: 'GPU instruments', description: 'Shape a live generated visual using its instrument parameters.' },
  riders: { title: 'Smoke and Fluid Riders', description: 'Shape fluid motion and the particles moving through it.' },
  'point-clouds': { title: 'Point clouds and splats', description: 'Position and style scanned three-dimensional content.' },
  effects: { title: 'Effects', description: 'Adjust an effect or its parameters. Effect order changes the resulting image.' },
  'custom-effects': { title: 'Custom effects', description: 'Load and control a custom effect plugin.' },
  'custom-shaders': { title: 'Shaders', description: 'Load a shader and adjust the inputs it exposes.' },
  'ai-generation': { title: 'AI generation', description: 'Configure and use the available generation tools.' },
  'midi-audio': { title: 'Audio and MIDI', description: 'Connect audio or a controller and synchronize or modulate your visuals.' },
  'pro-dj-link-osc': { title: 'OSC and DJ sync', description: 'Connect external control and tempo sources to the app.' },
  'keyboard-mapping': { title: 'Keyboard controls', description: 'Assign keyboard controls for performance.' },
  'mobile-control': { title: 'Mobile control', description: 'Connect a companion device to control your show.' },
  'recording-output': { title: 'Recording', description: 'Capture the composition and configure recording options.' },
  'frame-locked-export': { title: 'Offline export', description: 'Render a timed sequence frame by frame to a video file.' },
  'syphon-spout-ndi': { title: 'Video sharing', description: 'Exchange live video with compatible applications and devices.' },
  'render-core': { title: 'Native renderer', description: 'Inspect the native GPU renderer and its current status.' },
  performance: { title: 'Playback and performance', description: 'Choose media formats and quality settings appropriate to your show.' },
  wled: { title: 'WLED LED output', description: 'Connect a WLED controller, map LEDs to the composition, and check wiring with test patterns.' },
  settings: { title: 'Settings', description: 'Configure application preferences and connected devices.' },
  troubleshooting: { title: 'Troubleshooting', description: 'Check status and resolve problems with the app or connected devices.' },
};

const specific: [RegExp, string, string][] = [
  [/\bwled\b/i, 'wled', 'Send composition colors to a WLED controller on your local network. Open the setup guide for connection and mapping instructions.'],
  [/ableton link/i, 'midi-audio', 'Share tempo and beat phase with compatible Link applications on the network.'],
  [/offline render|frame.locked|export video/i, 'frame-locked-export', 'Render a timed sequence to a video file using a fixed frame clock.'],
  [/\brecord(?:ing)?\b/i, 'recording-output', 'Capture the composition using the recording options supported by this build. Clip audio playback and alpha import do not imply audio or alpha recording support.'],
  [/save.*project|open.*project|new.*project|composition as|project media|relink/i, 'projects', 'Manage the saved project and its referenced media. Save a copy before making changes to a show you need to preserve.'],
  [/\bwarp|corner.pin/i, 'projection-mapping', 'Adjust the mapping geometry to align content with the physical projection surface.'],
  [/\bslice source/i, 'masks-slices', 'Choose the VJ Mix, a row, or a group as this stage slice’s content. Its crop and geometry stay independent.'],
  [/\bmask\b/i, 'masks-slices', 'Control which parts of the content are visible on this surface.'],
  [/\bblend mode/i, 'layers', 'Choose how this layer’s colors combine with the content beneath it. Normal uses the source transparency.'],
  [/\bopacity\b/i, 'layers', 'Adjust how visible this layer or group is in the composite. Zero hides it; full opacity still respects the media’s alpha channel.'],
  [/effect.*preset|preset.*effect/i, 'effects', 'Save or recall an effect chain to reuse its look.'],
  [/modulation|\blfo\b/i, 'effects', 'Choose how this parameter moves over time, using the available audio, oscillator, beat or Auto sources.'],
  [/autopilot/i, 'clip-launcher', 'Automatically advance clips on this layer using the selected order. The A button toggles the layer’s autopilot.'],
  [/ignore column/i, 'clip-launcher', 'Keep this layer or clip out of column launches; manual launches remain available.'],
  [/fader start/i, 'clip-launcher', 'Restart the active video at trim-in when layer opacity rises from zero.'],
  [/layer lock|lock layer/i, 'clip-launcher', 'Protect this layer from clip launches until it is unlocked.'],
  [/quantiz|quantis|^quant$/i, 'clip-launcher', 'Choose the beat boundary for clip launches. Off launches immediately; other values intentionally wait for the clock.'],
  [/\bbpm\b|tap tempo/i, 'midi-audio', 'Set the performance tempo. Type a BPM for manual tempo, tap a beat, or follow a connected clock source.'],
  [/\bresync\b/i, 'midi-audio', 'Reset the local beat phase to the downbeat. External clock ownership can disable this control.'],
  [/\bnudge\b/i, 'midi-audio', 'Temporarily move the local tempo ahead or behind to align it with the music.'],
  [/\bcue point|cue pad/i, 'clip-launcher', 'Save a playback position in an empty pad; trigger a saved pad to jump there. Shift-click replaces it.'],
  [/\breverse\b/i, 'clip-launcher', 'Play the video toward earlier frames.'],
  [/\bforward\b/i, 'clip-launcher', 'Play the video toward later frames.'],
  [/\bbounce\b/i, 'clip-launcher', 'Alternate forward and reverse playback at the clip’s trim boundaries.'],
  [/\bscrub|playback position|seek/i, 'clip-launcher', 'Move the video playhead to a position. Drag back and forth to scratch the clip.'],
  [/\blut\b|\.cube/i, 'effects', 'Apply a 3D .cube color lookup table and adjust its strength. Imported tables are saved with the project.'],
  [/\bmacro/i, 'macros-snapshots', 'Use one of the eight top-row macro knobs to control assigned effect parameters with individual ranges.'],
  [/\bsnapshot|\bsnaps\b/i, 'macros-snapshots', 'Store or recall a performance look using the snapshot bank.'],
  [/\bmidi\b/i, 'midi-audio', 'Connect or map a MIDI controller to operate this control from hardware.'],
  [/\bosc\b/i, 'pro-dj-link-osc', 'Configure or use OSC messages to control the app from another application or device.'],
  [/\bsyphon|\bspout|\bndi\b/i, 'syphon-spout-ndi', 'Configure live video sharing with a compatible sender or receiver. Availability depends on the platform and installed build.'],
  [/\bconvert|hap alpha|prores/i, 'performance', 'Convert media for playback. HAP Alpha and ProRes 4444 Alpha preserve existing transparency; ordinary HAP and HAP Q do not.'],
];

export function helpContent(label: string, page = 'interface', description = '') {
  const match = specific.find(([pattern]) => pattern.test(label));
  const topic = Object.hasOwn(helpTopics, page) ? page : 'interface';
  return {
    title: label || helpTopics[topic].title,
    description: description || match?.[2] || helpTopics[topic].description,
    href: `https://ghostarcade.live/docs/${match?.[1] || topic}`,
  };
}
